name: Hotfix PR back to develop

on:
  pull_request:
    types: ['ready_for_review']
    branches:
      - master
      - release/*

permissions:
    pull-requests: read|write

jobs:
  build:
    name: Hotfix PR back to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: checkout to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.number }}

      - name: create PR to develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh pr create -B develop
          -t "[-> dev] ${{ github.event.pull_request.title }}"
          -b "ref #${{ github.event.number }}"
          -r "${{github.actor}}"
